services:
  os161:
    build:
      context: .
      dockerfile: Dockerfile
    image: cse4300-os161:latest
    container_name: os161
    tty: true
    stdin_open: true
    user: os161user
    working_dir: /home/os161user/work/os161
    volumes:
      - ./:/home/os161user/work
    command: ["/bin/bash"]